apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: komiser-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: komiser.seudominio.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: komiser-service
            port:
              number: 80
