apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: komiser-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps"]
  verbs: ["get", "list", "watch"]
